Repository Marli-Marlete/marli-music, pull requests merged in 2023-07, with the labels that each got.

#19 Feat/add shuffle
  src/bot/commands/command-map.ts
  src/bot/commands/command-shuffle.ts
  src/bot/commands/command.ts
  src/bot/commands/index.ts
  src/helpers/helpers.ts
  src/queue/queue.ts
  test/helpers/helpers.spec.ts
Labels: enhancement

#21 Spotify Playlist
  .eslintignore
  .gitignore
  src/bot/commands/command-list-queue.ts
  src/bot/commands/command-play.ts
  src/bot/commands/command-skip.ts
  src/bot/commands/command.ts
  src/bot/marli-music.ts
  src/helpers/helpers.ts
  src/queue/queue.ts
  src/sources/play-dl-source/play-dl-source.ts
  src/sources/play-dl-source/strategies/spotify-strategy.ts
  src/sources/play-dl-source/strategies/strategy.ts
  src/sources/play-dl-source/strategies/youtube-strategy.ts
  src/sources/source-stream.ts
  src/sources/ytdl-source/ytdl-source.ts
Labels: work in progress

#32 Add Spotify Album Feature
  src/sources/play-dl-source/auth.ts
  src/sources/play-dl-source/play-dl-source.ts
  src/sources/play-dl-source/strategies/spotify-strategy.ts
  src/sources/play-dl-source/strategies/strategy.ts
Labels: code review
